# Provisions an Azure PostgreSQL Flexible Server with specified configurations like version, storage, and admin credentials.
resource "azurerm_postgresql_flexible_server" "default" {
  # Defines the name of the PostgreSQL Flexible Server instance, using a prefix generated by a `random_pet` resource for uniqueness.
  name = "${random_pet.name_prefix.id}-server"

  # Specifies the name of the resource group where the PostgreSQL server will be located.
  resource_group_name = azurerm_resource_group.default.name

  # The Azure region where the PostgreSQL server will be deployed.
  location = azurerm_resource_group.default.location

  # The version of PostgreSQL to be deployed on the server.
  version = "16"

  # The ID of the delegated subnet within a virtual network where the PostgreSQL server will be connected, ensuring network isolation.
  delegated_subnet_id = azurerm_subnet.default.id

  # Associates the server with a private DNS zone for resolving the server's hostname within the virtual network.
  private_dns_zone_id = azurerm_private_dns_zone.default.id

  # The administrator username for the PostgreSQL server.
  administrator_login = "postgres"

  # The password for the PostgreSQL server administrator, generated by a `random_password` resource for security.
  administrator_password = random_password.pass.result

  # The availability zone where the server will be placed. Use "1", "2", or "3" for specific zones, or leave empty for no specific zone.
  zone = "1"

  # The amount of storage allocated for the server in megabytes.
  storage_mb = 32768

  # Specifies the SKU name for the server, determining the pricing tier and performance characteristics.
  sku_name = "B_Standard_B1ms"

  # The number of days backups are retained. Azure allows a minimum of 7 and a maximum of 35 days for backup retention.
  backup_retention_days = 7

  # Determines whether geo-redundant backups are enabled, providing additional data resiliency by storing backups in a secondary region.
  geo_redundant_backup_enabled = false

  # Specifies whether the server's storage should automatically grow as needed, preventing out-of-space errors.
  auto_grow_enabled = false

  # when you prefer maintenance to occur. Azure uses this information to schedule maintenance operations, such as updates and patches, minimizing impact on your service.
  maintenance_window {
    day_of_week  = 0  # 0 = Sunday, 1 = Monday, ..., 6 = Saturday
    start_hour   = 3  # 24-hour format UTC
    start_minute = 30 # Minute of the hour
  }

  /*
  # Configures the high availability (HA) settings for the PostgreSQL server to enhance fault tolerance and ensure service continuity.
  high_availability {
    # 'mode' determines the type of high availability configuration. 
    # "ZoneRedundant" places the standby server in a different availability zone from the primary server for increased resilience against zone failures.
    # "SameZone" places the standby server in the same availability zone as the primary server, which may offer lower latency during failover but doesn't protect against zone-wide issues.
    mode = "ZoneRedundant" # Or "SameZone" for single-zone high availability
  }
*/

  depends_on = [azurerm_private_dns_zone_virtual_network_link.default]
}

resource "azurerm_postgresql_flexible_server_database" "default" {
  name      = "${random_pet.name_prefix.id}-db"             # The name of the database, prefixed with the generated name to ensure uniqueness.
  server_id = azurerm_postgresql_flexible_server.default.id # Links the database to the created PostgreSQL server.
  collation = "en_US.utf8"                                  # Sets the database collation.
  charset   = "UTF8"                                        # Sets the database character set.

  # prevent the possibility of accidental data loss
  /*lifecycle {
    prevent_destroy = true
  }*/
}
